#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find -H ~/projects ~/nixos-setup -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

# my tmux start at index 1 : please read "tmux.conf"
create_session(){
    tmux new-session -ds "$selected_name" -c "$selected" || return $?
    tmux rename-window -t "=$selected_name:1" nvim || return $?
    tmux send-keys -t "=$selected_name:1" "nvim ." Enter || return $?
    tmux new-window -t "=$selected_name:" -n scratch -c "$selected" || return $?
}

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
    create_session || exit $?
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t "=$selected_name:1"
else
    tmux switch-client -t "=$selected_name:1"
fi
