#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/projects ~/nixos-setup -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -ds "$selected_name" -c "$selected"
    tmux rename-window -t "$selected_name:1" nvim
    tmux send-keys -t "$selected_name:1" "nvim ." Enter
    tmux new-window -t "$selected_name" -n scratch -c "$selected"
    tmux attach-session -t "$selected_name:1"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
    tmux rename-window -t "$selected_name:1" nvim
    tmux send-keys -t "$selected_name:1" "nvim ." Enter
    tmux new-window -t "$selected_name" -n scratch -c "$selected"
fi

tmux switch-client -t "$selected_name:1"
